# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAvaliador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=12)),
            ],
        ),
    ]
