# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAtleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=30)),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('data_nascimento', models.CharField(max_length=8)),
                ('cpf_cnpj', models.CharField(max_length=12)),
                ('ano_ini_esporte', models.CharField(max_length=12)),
                ('modalidade_principal', models.CharField(max_length=50)),
                ('vezes_treina', models.CharField(max_length=50)),
                ('duracao_treino', models.CharField(max_length=50)),
                ('horas_trein_semana', models.CharField(max_length=50)),
                ('horas_trein_cada_modalidae', models.CharField(max_length=50)),
                ('modalidade_frequente', models.CharField(max_length=50)),
                ('duracao_treino_longo', models.CharField(max_length=50)),
                ('profissao', models.CharField(max_length=50)),
                ('competicoes_frequenta', models.CharField(max_length=50)),
                ('duracao_provas', models.CharField(max_length=50)),
                ('tipo_de_relevo', models.CharField(max_length=50)),
                ('nivel_atleta', models.CharField(max_length=50)),
                ('outros', models.CharField(max_length=50)),
            ],
        ),
    ]
