# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20170222_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilatleta',
            name='nivel_atleta',
            field=models.CharField(choices=[('AM', 'Amador.'), ('AMF', 'Amador Forte.'), ('ARM', 'Alto Rendimento.'), ('ARMP', 'Alto Rendimento Profissional.'), ('RC', 'Recreacional.')], max_length=50, verbose_name='Selecione o nível do atleta.'),
        ),
    ]
