# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20170223_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilatleta',
            name='cpf_cnpj',
            field=models.CharField(max_length=12, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='perfilatleta',
            name='modalidade_principal',
            field=models.CharField(choices=[('MP', '--- Modalide principal ---'), ('MT', 'MTB'), ('CICL', 'Ciclismo'), ('TRIL', 'Triathlon'), ('OU', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilatleta',
            name='nivel_atleta',
            field=models.CharField(choices=[('', '--- Nível do atleta ---'), ('AM', 'Amador'), ('AMF', 'Amador Forte'), ('ALR', 'Alto Rendimento'), ('ALRP', 'Alto Rendimento Profissional'), ('RE', 'Recreacional')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilatleta',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='perfilatleta',
            name='tipo_de_relevo',
            field=models.CharField(choices=[('TO', '--- Tipo relevo ---'), ('PL', 'Plano'), ('PS', 'Pouco de subidas'), ('MS', 'Muitas subidas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilatleta',
            name='vezes_treina',
            field=models.CharField(choices=[('TR', '--- Treinos por semana ---'), ('UM', '1'), ('DOIS', '2'), ('TRES', '3'), ('QUATRO', '4'), ('CINCO', '5'), ('SEIS', '6'), ('SETE', '7')], max_length=50),
        ),
        migrations.AlterField(
            model_name='perfilavaliador',
            name='cpf_cnpj',
            field=models.CharField(max_length=12, verbose_name='CPF/CNPJ'),
        ),
    ]
