from django import forms
from .models import PerfilAvaliador, PerfilAtleta, AvaliacaoPostural

class PerfilAvaliadorForm(forms.ModelForm):
    class Meta:
        model = PerfilAvaliador
        fields = '__all__'
        exclude = ['create', 'update']
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome do avaliador.'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email, Ex: email@suedcorps.com.'}),
            'telefone': forms.TextInput(attrs={'placeholder': 'Telefone, Ex: DDD 99999-9999.'}),
            'cidade': forms.TextInput(attrs={'placeholder': 'Cidade, Ex: São Paulo - SP.'}),
            'endereco': forms.TextInput(attrs={'placeholder': 'Endereço, Ex: Rua São João, 9999 - Centro.'}),
            'empresa': forms.TextInput(attrs={'placeholder': 'Empresa, Ex: Sued Corps.'}),
            'cpf_cnpj': forms.TextInput(attrs={'placeholder': 'CPF/CNPJ, Ex: 999.999.999-46 / 99.999.999/0001-99.'}),
        }

class PerfilAtletaForm(forms.ModelForm):
    class Meta:
        model = PerfilAtleta
        fields = '__all__'
        exclude = ['create', 'update']
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Nome do atleta.'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Email, Ex: email@suedcorps.com.'}),
            'telefone': forms.TextInput(attrs={'placeholder': 'Telefone, Ex: DDD 99999-9999.'}),
            'cidade': forms.TextInput(attrs={'placeholder': 'Cidade, Ex: São Paulo - SP.'}),
            'endereco': forms.TextInput(attrs={'placeholder': 'Endereço, Ex: Rua São João, 9999 - Centro.'}),
            'data_nascimento': forms.DateInput(attrs={'placeholder': 'Nascimento, Ex: 1991-26-91'}, format='%d-%m-%Y'),
            'cpf_cnpj': forms.TextInput(attrs={'placeholder': 'CPF/CNPJ, Ex: 999.999.999-46 / 99.999.999/0001-99.'}),
            'rg': forms.NumberInput(),
            'ano_ini_esporte': forms.TextInput(attrs={'placeholder': 'Ano início do esporte, Ex: 2017.'}),
            'modalidade_principal': forms.Select(attrs={'placeholder': 'Modalidade principal, Ex: Speed de Estrada.'}),
            'vezes_treina': forms.NumberInput(attrs={'placeholder': 'Vezes que treina por semana.'}),
            'duracao_treino': forms.NumberInput(attrs={'placeholder': 'Duração média dos treinos'}),
            'horas_trein_semana': forms.NumberInput(attrs={'placeholder': 'Horas treino por semana.'}),
            'duracao_treino_longo': forms.TextInput(attrs={'placeholder': 'Duração do treino mais longo, Ex: 5 hrs.'}),
            'modalidade_frequente': forms.TextInput(attrs={'placeholder': 'Modalidade treino frequente, Ex: Speed de Estrada.'}),
            'profissao': forms.TextInput(attrs={'placeholder': 'Profissão, Ex: Encanador.'}),
            'competicoes_frequenta': forms.Textarea(attrs={'placeholder': 'Competições que frequenta, Ex: Speed X MTB.'}),
            'duracao_provas': forms.TextInput(attrs={'placeholder': 'Duração das provas, Ex: 5 hrs.'}),
            'tipo_de_relevo': forms.Select(attrs={'placeholder': 'Tipo relevo, Ex: Plano, pouco de subida ou muita subida.'}),
            'nivel_atleta': forms.Select(attrs={'placeholder': 'Nivel do atleta, Ex: iniciante.'}),
            'outros': forms.Textarea(attrs={'placeholder': 'Comentários adicionais.'}),
            # 'foto': forms.FileInput(attrs={'placeholder': 'Selecione suas fotos.'}),
        }

class AvaliacaoPosturalForm(forms.ModelForm):
    class Meta:
        model = AvaliacaoPostural
        fields = '__all__'
        exclude = ['create', 'update']
        widgets = {
            'jl_L_Shoulder_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Shoulder'}),
            'jl_L_Shoulder_swol': forms.CheckboxInput(attrs={'name': 'L_Shoulder'}),
            'jl_R_Shoulder_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Shoulder'}),
            'jl_R_Shoulder_swol': forms.CheckboxInput({'name': 'R_Shoulder'}),
            'jl_L_Elbow_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Elbow'}),
            'jl_L_Elbow_swol': forms.CheckboxInput({'name': 'L_Elbow'}),
            'jl_R_Elbow_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Elbow'}),
            'jl_R_Elbow_swol': forms.CheckboxInput({'name': 'R_Elbow'}),
            'jl_L_Wrist_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Wrist'}),
            'jl_L_Wrist_swol': forms.CheckboxInput({'name': 'L_Wrist'}),
            'jl_R_Wrist_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Wrist'}),
            'jl_R_Wrist_swol': forms.CheckboxInput({'name': 'R_Wrist'}),
            'jl_C_Spine_tend': forms.TextInput(attrs={'placeholder': '','name': 'C_Spine'}),
            'jl_C_Spine_swol': forms.CheckboxInput({'name': 'C_Spine'}),
            'jl_T_Spine_tend': forms.TextInput(attrs={'placeholder': '','name': 'T_Spine'}),
            'jl_T_Spine_swol': forms.CheckboxInput({'name': 'T_Spine'}),
            'jl_L_Spine_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Spine'}),
            'jl_L_Spine_swol': forms.CheckboxInput({'name': 'L_Spine'}),
            'jl_L_Hip_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Hip'}),
            'jl_L_Hip_swol': forms.CheckboxInput({'name': 'L_Hip'}),
            'jl_R_Hip_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Hip'}),
            'jl_R_Hip_swol': forms.CheckboxInput({'name': 'R_Hip'}),
            'jl_L_Knee_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Knee'}),
            'jl_L_Knee_swol': forms.CheckboxInput({'name': 'L_Knee'}),
            'jl_R_Knee_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Knee'}),
            'jl_R_Knee_swol': forms.CheckboxInput({'name': 'R_Knee'}),
            'jl_L_Ankle_tend': forms.TextInput(attrs={'placeholder': '','name': 'L_Ankle'}),
            'jl_L_Ankle_swol': forms.CheckboxInput({'name': 'L_Ankle'}),
            'jl_R_Ankle_tend': forms.TextInput(attrs={'placeholder': '','name': 'R_Ankle'}),
            'jl_R_Ankle_swol': forms.CheckboxInput({'name': 'R_Ankle'}),
            'jl_L_Shoulder_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Shoulder'}),
            'jl_L_Shoulder_swol2': forms.CheckboxInput(attrs={'name': 'L_Shoulder'}),
            'jl_R_Shoulder_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Shoulder'}),
            'jl_R_Shoulder_swol2': forms.CheckboxInput(attrs={'name': 'R_Shoulder'}),
            'jl_L_Elbow_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Elbow'}),
            'jl_L_Elbow_swol2': forms.CheckboxInput(attrs={'name': 'L_Elbow'}),
            'jl_R_Elbow_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Elbow'}),
            'jl_R_Elbow_swol2': forms.CheckboxInput(attrs={'name': 'R_Elbow'}),
            'jl_L_Wrist_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Wrist'}),
            'jl_L_Wrist_swol2': forms.CheckboxInput({'name': 'L_Wrist'}),
            'jl_R_Wrist_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Wrist'}),
            'jl_R_Wrist_swol2': forms.CheckboxInput({'name': 'R_Wrist'}),
            'jl_C_Spine_tend2': forms.TextInput(attrs={'placeholder': '','name': 'C_Spine'}),
            'jl_C_Spine_swol2': forms.CheckboxInput({'name': 'C_Spine'}),
            'jl_T_Spine_tend2': forms.TextInput(attrs={'placeholder': '','name': 'T_Spine'}),
            'jl_T_Spine_swol2': forms.CheckboxInput({'name': 'T_Spine'}),
            'jl_L_Spine_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Spine'}),
            'jl_L_Spine_swol2': forms.CheckboxInput({'name': 'L_Spine'}),
            'jl_L_Hip_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Hip'}),
            'jl_L_Hip_swol2': forms.CheckboxInput({'name': 'L_Hip'}),
            'jl_R_Hip_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Hip'}),
            'jl_R_Hip_swol2': forms.CheckboxInput({'name': 'R_Hip'}),
            'jl_L_Knee_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Knee'}),
            'jl_L_Knee_swol2': forms.CheckboxInput({'name': 'L_Knee'}),
            'jl_R_Knee_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Knee'}),
            'jl_R_Knee_swol2': forms.CheckboxInput({'name': 'R_Knee'}),
            'jl_L_Ankle_tend2': forms.TextInput(attrs={'placeholder': '','name': 'L_Ankle'}),
            'jl_L_Ankle_swol2': forms.CheckboxInput({'name': 'L_Ankle'}),
            'jl_R_Ankle_tend2': forms.TextInput(attrs={'placeholder': '','name': 'R_Ankle'}),
            'jl_R_Ankle_swol2': forms.CheckboxInput({'name': 'R_Ankle'}),
            'nivel_flexibilidade_quadril': forms.Select({'placeholder': 'Flexibilidade Quadril'}),
            'nivel_flexibilidade_joelho': forms.Select({'placeholder': 'Flexibilidade Joelho'}),
            'nivel_flexibilidade_ombro': forms.Select({'placeholder': 'Flexibilidade Ombro'}),
            'escoliose': forms.TextInput({'placeholder': 'Escoliose'}),
            'escoliose_comen': forms.TextInput({'placeholder': 'Escoliose Comentarios'}),
            'lombares': forms.TextInput({'placeholder': 'Lombares'}),
            'cervicais': forms.TextInput({'placeholder': 'Cervicais'}),
            'cifose': forms.TextInput({'placeholder': 'Cifose'}),
            'mobilidade_quadril': forms.TextInput({'placeholder': 'Mobilidade do Quadril'}),
            'joelho_desvio_lat': forms.TextInput({'placeholder': 'Joelho Desvio Lateral'}),
            'joelho_desvio_ant': forms.TextInput({'placeholder': 'Joelho Desvio Anteposterior'}),
            'pe': forms.TextInput({'placeholder': 'Pé'}),
            'ombro': forms.TextInput({'placeholder': 'Ombro'}),
            'cotovelo': forms.TextInput({'placeholder': 'Cotovelo'}),
            'maos': forms.TextInput({'placeholder': 'Mãos'}),
            'assimetria_pernas': forms.TextInput({'placeholder': 'Assimetria das Pernas'}),
            'assimetrias_braco': forms.TextInput({'placeholder': 'Assimetria dos Braços'}),
            'tibia': forms.NumberInput({'placeholder': 'Tibia'}),
            'femur': forms.NumberInput({'placeholder': 'Fêmur'}),
            'tronco': forms.NumberInput({'placeholder': 'Tronco'}),
            'umero': forms.NumberInput({'placeholder': 'Umero'}),
            'radio': forms.NumberInput({'placeholder': 'Radio'}),
            'quadril': forms.NumberInput({'placeholder': 'Quadril'}),
            'ombroS': forms.NumberInput({'placeholder': 'Ombro'}),
            'cabeca': forms.NumberInput({'placeholder': 'Cabeça'}),
            'isquios': forms.NumberInput({'placeholder': 'Isquios'}),
            'peM': forms.NumberInput({'placeholder': 'Pe'}),
            'ombroM': forms.NumberInput({'placeholder': 'Ombros'}),
            'bracosM': forms.NumberInput({'placeholder': 'Braços'}),
            'cavalM': forms.NumberInput({'placeholder': 'Cavalo'}),
            'troncoCava': forms.NumberInput({'placeholder': 'Tronco + Cavalo'}),
            'altura': forms.NumberInput({'placeholder': 'Altura'}),
            'larguraselim': forms.TextInput({'placeholder': 'Largura do Selim'}),
            'tamanhobike': forms.TextInput({'placeholder': 'Tamanho da Bike'}),
            'formatoguidao': forms.TextInput({'placeholder': 'Formato do Guidão'}),
            'tamanhopevela': forms.TextInput({'placeholder': 'Tamanho do pé de vela'}),
            'comentariosgerais': forms.TextInput({'placeholder': 'Comentários Gerais'}),

        }